language: java
sudo: true
dist: xenial

jdk:
- openjdk12

script:
- sudo snap install minizinc --classic
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
- mvn -pl '!build-common' jacoco:report coveralls:report
