/*
 * Copyright 2018-2020 VMware, Inc. All Rights Reserved.
 *
 * SPDX-License-Identifier: BSD-2
 */

package com.vmware.dcm.compiler;

import com.vmware.dcm.ViewsWithAnnotations;

import javax.annotation.concurrent.NotThreadSafe;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Used to track the set of symbol references from the constraint-views.
 */
@NotThreadSafe
class ReferencedSymbols {
    // From the AST generated by parsing SQL
    private final Map<String, ViewsWithAnnotations> nonConstraintViews;
    private final Map<String, ViewsWithAnnotations> constraintViews;
    private final Map<String, ViewsWithAnnotations> objectiveFunctionViews;

    ReferencedSymbols() {
        nonConstraintViews = new LinkedHashMap<>();
        constraintViews = new LinkedHashMap<>();
        objectiveFunctionViews = new LinkedHashMap<>();
    }

    Map<String, ViewsWithAnnotations> getNonConstraintViews() {
        return nonConstraintViews;
    }

    Map<String, ViewsWithAnnotations> getObjectiveFunctionViews() {
        return objectiveFunctionViews;
    }

    Map<String, ViewsWithAnnotations> getConstraintViews() {
        return constraintViews;
    }

    void printKeys() {
        System.out.println("----------");
        System.out.println("NonConstraintViews: " + nonConstraintViews.keySet());
        System.out.println("ConstraintViews: " + constraintViews.keySet());
        System.out.println("----------");
    }
}