/*
 *
 *  * Copyright © 2017 - 2018 VMware, Inc. All Rights Reserved.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the “License”); you may not use this file
 *  * except in compliance with the License. You may obtain a copy of the License at
 *  * http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software distributed under the
 *  * License is distributed on an “AS IS” BASIS, without warranties or conditions of any kind,
 *  * EITHER EXPRESS OR IMPLIED. See the License for the specific language governing
 *  * permissions and limitations under the License.
 *
 */

package com.vrg.compiler;

import com.facebook.presto.sql.tree.Query;

import javax.annotation.concurrent.NotThreadSafe;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Used to track the set of symbol references from the constraint-views.
 */
@NotThreadSafe
class ReferencedSymbols {
    // From the AST generated by parsing SQL
    private final Map<String, Query> nonConstraintViews;
    private final Map<String, Query> constraintViews;
    private final Map<String, Query> objectiveFunctionViews;

    ReferencedSymbols() {
        nonConstraintViews = new LinkedHashMap<>();
        constraintViews = new LinkedHashMap<>();
        objectiveFunctionViews = new LinkedHashMap<>();
    }

    Map<String, Query> getNonConstraintViews() {
        return nonConstraintViews;
    }

    Map<String, Query> getObjectiveFunctionViews() {
        return objectiveFunctionViews;
    }

    Map<String, Query> getConstraintViews() {
        return constraintViews;
    }

    void printKeys() {
        System.out.println("----------");
        System.out.println("NonConstraintViews: " + nonConstraintViews.keySet());
        System.out.println("ConstraintViews: " + constraintViews.keySet());
        System.out.println("----------");
    }
}