apiVersion: v1
kind: Pod
metadata:
  name: cache
  labels:
    app: store
spec:
  schedulerName: default-scheduler
  containers:
    - name: cache
      image: registry.k8s.io/pause
      imagePullPolicy: IfNotPresent
