apiVersion: v1
kind: Pod
metadata:
  name: cache
  labels:
    app: store
spec:
  schedulerName: default-scheduler
  containers:
    - name: cache
      image: k8s.gcr.io/pause
      imagePullPolicy: IfNotPresent
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - store
          topologyKey: kubernetes.io/hostname
